package:
  name: brightway_projects-dev
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - appdirs
    - peewee

test:
  imports:
    - brightway_projects

about:
  home: "https://github.com/brightway-lca/brightway_projects"
  license: BSD License
  summary: 'Manager for Brightway LCA libraries and projects'
license_family: BSD
